name: "[CICD] Superset"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Manual environment to run (qa | staging | prod)"
        required: false
        type: string
  push:
    branches:
      - main
      - master
      - release
      - feat-build-pipeline

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  SERVICE_NAME: superset
  SERVICE_PATH: '.'

jobs:
  set_env:
    runs-on: ubuntu-latest
    name: Set Environment
    steps:
      - name: Set environment base on branch
        id: set_env
        run: |
          if [[ ${{ github.ref_name }} == 'staging' ]]; then
            echo "ENV=staging" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref_name }} == 'main' || ${{ github.ref_name }} == 'master' ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          fi
    outputs:
      ENV: ${{ inputs.environment || steps.set_env.outputs.ENV }}

  build_backend:
    runs-on: self-hosted-medium
    needs: [set_env]
    name: Build Backend
    environment: ${{ needs.set_env.outputs.ENV }}
    steps:
      - uses: actions/checkout@v3
      ### Set additional vars
      - name: Set additional vars
        id: set_outputs
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          IMAGE_REGISTRY="${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
          IMAGE_REPO="${{ env.SERVICE_NAME }}"
          IMAGE_VERSION="${{ github.ref_name }}-${SHA_SHORT}-${{ vars.IMAGE_ARCH }}"
          IMAGE_TAG="${IMAGE_REGISTRY}/${IMAGE_REPO}:${IMAGE_VERSION}"
          IMAGE_TAG_LT="${IMAGE_REGISTRY}/${IMAGE_REPO}:latest"
          IMAGE_TAG_LT_ARCH="${IMAGE_REGISTRY}/${IMAGE_REPO}:latest-${{ vars.IMAGE_ARCH }}"

          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG_LT=${IMAGE_TAG_LT}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG_LT_ARCH=${IMAGE_TAG_LT_ARCH}" >> $GITHUB_OUTPUT
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        shell: bash
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders
      ### AWS Config
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/katalon-github-oidc-federation
          role-session-name: github-actions
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: 'no'
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.SERVICE_PATH }}
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.set_outputs.outputs.IMAGE_TAG }},
            ${{ steps.set_outputs.outputs.IMAGE_TAG_LT }},
            ${{ steps.set_outputs.outputs.IMAGE_TAG_LT_ARCH }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: platform/${{ vars.IMAGE_ARCH }}